import type { Question } from "@/types";

/**
 * NUST-NET question bank — 120 real, hand-solved MCQs.
 *
 * Section budgets (exact): Mathematics 36, Physics 30, Chemistry 24,
 * English 18, Intelligence 12.
 *
 * Topic/subtopic names match nust.ts taxonomy exactly. Every taxonomy
 * subtopic is covered; all but four have >= 2 questions. The four
 * singletons (Kinetic Theory, Heat Transfer, Atomic Models,
 * Nuclear Physics) are forced by arithmetic, not oversight: Physics owns
 * 17 subtopics, and universal >= 2 coverage would need 34 slots against a
 * budget of 30.
 *
 * Conventions: Unicode math only (x², √, π, θ, ×, ±, ∞, ÷, ≤, ≥, ≠, →,
 * ⇌, subscripts). No caret notation, no "Drill"/"Practice"/"Stand-in"
 * prefixes, isPlaceholder: false, exactly one correct answer.
 */
export const nustBank: Question[] = [
  // ================= MATHEMATICS — ALGEBRA (10) =================
  {
    id: "bank-math-algebra-01",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Quadratic Equations",
    text: "The roots of x² − 5x + 6 = 0 are:",
    options: ["2 and 3", "1 and 6", "−2 and −3", "0 and 5"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-02",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Quadratic Equations",
    text: "The quadratic equation with roots 3 and −2 is:",
    options: ["x² − x − 6 = 0", "x² + x − 6 = 0", "x² − x + 6 = 0", "x² + x + 6 = 0"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-03",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Quadratic Equations",
    text: "The discriminant of 2x² − 4x + 1 = 0 is:",
    options: ["8", "0", "−8", "16"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-04",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Quadratic Equations",
    text: "If x² + kx + 9 = 0 has equal roots, then k =:",
    options: ["±6", "6 only", "−6 only", "±3"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-05",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Sequences & Series",
    text: "The 5th term of the geometric sequence 2, 6, 18, … is:",
    options: ["162", "54", "486", "108"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-06",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Sequences & Series",
    text: "The sum of the infinite geometric series 1 + 1/2 + 1/4 + … is:",
    options: ["2", "1", "3/2", "4"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-08",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Complex Numbers",
    text: "The value of i⁴ is:",
    options: ["1", "i", "−1", "−i"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-09",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Complex Numbers",
    text: "The modulus of 3 + 4i is:",
    options: ["5", "7", "12", "25"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-10",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Matrices",
    text: "The determinant of [[2, 0], [0, 3]] is:",
    options: ["6", "5", "0", "1"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-algebra-11",
    section: "Mathematics",
    topic: "Algebra",
    subtopic: "Matrices",
    text: "Adding [[1, 2], [3, 4]] and [[0, 1], [1, 0]] gives:",
    options: ["[[1, 3], [4, 4]]", "[[1, 2], [3, 4]]", "[[0, 2], [3, 0]]", "[[1, 1], [2, 4]]"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= MATHEMATICS — CALCULUS (9) =================
  {
    id: "bank-math-calculus-01",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Differentiation",
    text: "d/dx (x³) equals:",
    options: ["3x²", "x²", "3x", "x³/3"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-02",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Differentiation",
    text: "d/dx (sin x) equals:",
    options: ["cos x", "−cos x", "−sin x", "tan x"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-03",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Differentiation",
    text: "d/dx (eˣ) equals:",
    options: ["eˣ", "x eˣ⁻¹", "1", "ln x"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-04",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Integration",
    text: "∫ 2x dx equals:",
    options: ["x² + C", "2 + C", "x + C", "2x² + C"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-05",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Integration",
    text: "∫ cos x dx equals:",
    options: ["sin x + C", "−sin x + C", "cos x + C", "−cos x + C"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-06",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Limits",
    text: "lim (x→0) (sin x)/x equals:",
    options: ["1", "0", "∞", "−1"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-07",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Limits",
    text: "lim (x→3) (x² − 9)/(x − 3) equals:",
    options: ["6", "3", "9", "0"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-08",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Differential Equations",
    text: "The order of d²y/dx² + 4 dy/dx + 3y = 0 is:",
    options: ["2", "1", "3", "0"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-calculus-09",
    section: "Mathematics",
    topic: "Calculus",
    subtopic: "Differential Equations",
    text: "dy/dx = 3x² with y(0) = 1 has the solution:",
    options: ["y = x³ + 1", "y = x³", "y = x³ − 1", "y = 3x³ + 1"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= MATHEMATICS — ANALYTIC GEOMETRY (7) =================
  {
    id: "bank-math-geometry-01",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Lines & Circles",
    text: "The slope of y = 2x + 3 is:",
    options: ["2", "3", "−2", "1/2"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-geometry-02",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Lines & Circles",
    text: "The distance between (0, 0) and (3, 4) is:",
    options: ["5", "7", "12", "25"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-geometry-03",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Lines & Circles",
    text: "The equation of a circle with center (0, 0) and radius 5 is:",
    options: ["x² + y² = 25", "x² + y² = 5", "(x − 5)² + y² = 0", "x + y = 5"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-geometry-04",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Conic Sections",
    text: "The eccentricity of a circle is:",
    options: ["0", "1", "∞", "2"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-geometry-05",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Conic Sections",
    text: "A parabola y² = 4ax with a > 0 opens toward the:",
    options: ["right", "left", "top", "bottom"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-geometry-06",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Vectors",
    text: "The dot product of (1, 0) and (0, 1) is:",
    options: ["0", "1", "2", "−1"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  {
    id: "bank-math-geometry-07",
    section: "Mathematics",
    topic: "Analytic Geometry",
    subtopic: "Vectors",
    text: "The magnitude of the vector (3, 4) is:",
    options: ["5", "7", "12", "25"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= MATHEMATICS — TRIGONOMETRY (6) =================
  {
    id: "bank-math-trig-01",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Identities",
    text: "sin² x + cos² x equals:",
    options: ["1", "0", "2", "tan x"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-trig-02",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Identities",
    text: "1 + tan² x equals:",
    options: ["sec² x", "cos² x", "sin² x", "csc² x"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-trig-03",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Equations",
    text: "One solution of sin x = 0 is:",
    options: ["x = 0", "x = π/2", "x = π/4", "x = π/3"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-trig-04",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Equations",
    text: "If sin θ = 1/2 with θ acute, then θ =:",
    options: ["30°", "60°", "45°", "90°"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-trig-05",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Triangle Solutions",
    text: "In a right triangle with opposite 3 and hypotenuse 5, sin θ =:",
    options: ["3/5", "4/5", "5/3", "3/4"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-trig-06",
    section: "Mathematics",
    topic: "Trigonometry",
    subtopic: "Triangle Solutions",
    text: "A right triangle has legs 3 and 4. Its hypotenuse is:",
    options: ["5", "7", "12", "25"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= MATHEMATICS — PROBABILITY (4) =================
  {
    id: "bank-math-prob-01",
    section: "Mathematics",
    topic: "Probability",
    subtopic: "Basic Probability",
    text: "A fair die is rolled. The probability of a 4 is:",
    options: ["1/6", "1/4", "1/3", "1/2"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-prob-02",
    section: "Mathematics",
    topic: "Probability",
    subtopic: "Basic Probability",
    text: "A fair coin is tossed twice. The probability of two heads is:",
    options: ["1/4", "1/2", "3/4", "1/8"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-prob-03",
    section: "Mathematics",
    topic: "Probability",
    subtopic: "Distributions",
    text: "A fair coin tossed 100 times: the expected number of heads is:",
    options: ["50", "100", "25", "0"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-math-prob-04",
    section: "Mathematics",
    topic: "Probability",
    subtopic: "Distributions",
    text: "A binomial experiment has n = 20 trials with success probability 1/2. The expected number of successes is:",
    options: ["10", "20", "5", "1"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= PHYSICS — MECHANICS (10) =================
  {
    id: "bank-phys-mech-01",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Kinematics",
    text: "A body at rest accelerates at 2 m/s² for 3 s. Its final velocity is:",
    options: ["6 m/s", "3 m/s", "9 m/s", "12 m/s"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-02",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Kinematics",
    text: "The area under a velocity-time graph gives:",
    options: ["displacement", "acceleration", "force", "momentum"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-03",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Newton Laws",
    text: "A 2 kg mass under a 10 N net force accelerates at:",
    options: ["5 m/s²", "20 m/s²", "2 m/s²", "0.2 m/s²"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-04",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Newton Laws",
    text: "Action and reaction forces are:",
    options: ["equal and opposite", "equal and in the same direction", "unequal and opposite", "unequal and in the same direction"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-05",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Work Energy Power",
    text: "100 J of work done in 20 s is a power of:",
    options: ["5 W", "2000 W", "120 W", "80 W"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-06",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Work Energy Power",
    text: "A 2 kg mass moving at 3 m/s has kinetic energy of:",
    options: ["9 J", "6 J", "18 J", "3 J"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-07",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Rotational Motion",
    text: "The SI unit of torque is:",
    options: ["N·m", "N/m", "J/s", "N·s"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-08",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Rotational Motion",
    text: "Angular momentum is conserved when the net external torque is:",
    options: ["zero", "maximum", "constant and nonzero", "infinite"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-09",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Gravitation",
    text: "The gravitational force between two masses quadruples when the distance between them is:",
    options: ["halved", "doubled", "quadrupled", "left unchanged"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-mech-10",
    section: "Physics",
    topic: "Mechanics",
    subtopic: "Gravitation",
    text: "The value of g at the centre of the Earth is:",
    options: ["zero", "9.8 m/s²", "maximum", "infinite"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= PHYSICS — THERMODYNAMICS (4) =================
  {
    id: "bank-phys-thermo-01",
    section: "Physics",
    topic: "Thermodynamics",
    subtopic: "Laws of Thermodynamics",
    text: "The first law of thermodynamics is a statement of conservation of:",
    options: ["energy", "momentum", "charge", "mass"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-thermo-02",
    section: "Physics",
    topic: "Thermodynamics",
    subtopic: "Laws of Thermodynamics",
    text: "An ideal gas is compressed isothermally. Its internal energy:",
    options: ["stays the same", "increases", "decreases", "becomes zero"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-thermo-03",
    section: "Physics",
    topic: "Thermodynamics",
    subtopic: "Kinetic Theory",
    text: "The average kinetic energy of an ideal gas molecule is proportional to:",
    options: ["absolute temperature", "pressure", "volume", "mass only"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-thermo-04",
    section: "Physics",
    topic: "Thermodynamics",
    subtopic: "Heat Transfer",
    text: "The SI unit of heat is:",
    options: ["joule", "watt", "newton", "degree Celsius"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= PHYSICS — ELECTROMAGNETISM (8) =================
  {
    id: "bank-phys-em-01",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Electrostatics",
    text: "Two like charges:",
    options: ["repel each other", "attract each other", "cancel each other", "exert no force"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-02",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Electrostatics",
    text: "The electric field inside a hollow charged conductor is:",
    options: ["zero", "maximum", "uniform and nonzero", "infinite"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-03",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Current Electricity",
    text: "A 12 V source across a 4 Ω resistor produces a current of:",
    options: ["3 A", "48 A", "8 A", "16 A"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-04",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Current Electricity",
    text: "Three 2 Ω resistors in series have a total resistance of:",
    options: ["6 Ω", "2/3 Ω", "3/2 Ω", "1 Ω"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-05",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Magnetism",
    text: "A charged particle moving parallel to a magnetic field experiences a force of:",
    options: ["zero", "maximum", "half the maximum", "infinite"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-06",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "Magnetism",
    text: "The SI unit of magnetic flux density is the:",
    options: ["tesla", "weber", "ampere", "volt"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-07",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "AC Circuits",
    text: "In a purely resistive AC circuit, current and voltage are:",
    options: ["in phase", "90° out of phase", "180° out of phase", "270° out of phase"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-em-08",
    section: "Physics",
    topic: "Electromagnetism",
    subtopic: "AC Circuits",
    text: "In a purely capacitive AC circuit, the current:",
    options: ["leads the voltage by 90°", "lags the voltage by 90°", "is in phase with the voltage", "is always zero"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= PHYSICS — OPTICS (4) =================
  {
    id: "bank-phys-optics-01",
    section: "Physics",
    topic: "Optics",
    subtopic: "Ray Optics",
    text: "The speed of light in vacuum is approximately:",
    options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-optics-02",
    section: "Physics",
    topic: "Optics",
    subtopic: "Ray Optics",
    text: "A convex lens is:",
    options: ["converging", "diverging", "neither converging nor diverging", "flat"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-optics-03",
    section: "Physics",
    topic: "Optics",
    subtopic: "Wave Optics",
    text: "Light is:",
    options: ["a transverse wave", "a longitudinal wave", "a sound wave", "a purely mechanical wave"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-optics-04",
    section: "Physics",
    topic: "Optics",
    subtopic: "Wave Optics",
    text: "In Young's double-slit experiment, increasing the light's wavelength:",
    options: ["increases the fringe width", "decreases the fringe width", "leaves the fringe width unchanged", "makes the fringes vanish entirely"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= PHYSICS — MODERN PHYSICS (4) =================
  {
    id: "bank-phys-modern-01",
    section: "Physics",
    topic: "Modern Physics",
    subtopic: "Photoelectric Effect",
    text: "In the photoelectric effect, increasing the light intensity increases the:",
    options: ["number of emitted electrons", "kinetic energy of each electron", "threshold frequency", "work function"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-modern-02",
    section: "Physics",
    topic: "Modern Physics",
    subtopic: "Photoelectric Effect",
    text: "The photoelectric effect demonstrates that light has:",
    options: ["particle nature", "purely wave nature", "magnetic charge", "infinite speed"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-modern-03",
    section: "Physics",
    topic: "Modern Physics",
    subtopic: "Atomic Models",
    text: "The Bohr model successfully explains the spectrum of:",
    options: ["hydrogen", "helium", "lithium", "uranium"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-phys-modern-04",
    section: "Physics",
    topic: "Modern Physics",
    subtopic: "Nuclear Physics",
    text: "The SI unit of radioactivity is the:",
    options: ["becquerel", "joule", "volt", "tesla"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= CHEMISTRY — PHYSICAL (9) =================
  {
    id: "bank-chem-physical-01",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Atomic Structure",
    text: "Electrons were discovered through:",
    options: ["cathode ray experiments", "alpha particle scattering", "the photoelectric effect", "X-ray diffraction"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-02",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Atomic Structure",
    text: "The nucleus of an atom contains:",
    options: ["protons and neutrons", "protons and electrons", "neutrons and electrons", "protons only"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-03",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Atomic Structure",
    text: "The atomic number of an element equals its number of:",
    options: ["protons", "neutrons", "nucleons", "electrons"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-04",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Chemical Bonding",
    text: "Sodium chloride is held together by:",
    options: ["ionic bonding", "covalent bonding", "metallic bonding", "hydrogen bonding"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-05",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Chemical Bonding",
    text: "A double covalent bond involves the sharing of:",
    options: ["two electron pairs", "one electron pair", "three electron pairs", "oppositely charged ions"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-06",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Thermochemistry",
    text: "A reaction that releases heat is called:",
    options: ["exothermic", "endothermic", "isothermal", "adiabatic"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-07",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Thermochemistry",
    text: "The heat content of a system at constant pressure is its:",
    options: ["enthalpy", "entropy", "internal energy", "free energy"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-08",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Equilibrium",
    text: "At equilibrium, the rates of the forward and reverse reactions are:",
    options: ["equal", "both zero", "forward greater", "reverse greater"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-physical-09",
    section: "Chemistry",
    topic: "Physical Chemistry",
    subtopic: "Equilibrium",
    text: "For N₂ + 3H₂ ⇌ 2NH₃, raising the pressure at equilibrium:",
    options: ["favours the forward reaction", "favours the reverse reaction", "has no effect", "stops the reaction"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= CHEMISTRY — INORGANIC (6) =================
  {
    id: "bank-chem-inorganic-01",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "Periodic Properties",
    text: "The most electronegative element is:",
    options: ["fluorine", "oxygen", "chlorine", "sodium"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-inorganic-02",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "Periodic Properties",
    text: "Atomic radius generally across a period from left to right:",
    options: ["decreases", "increases", "stays the same", "varies randomly"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-inorganic-03",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "p-block",
    text: "Carbon belongs to which block of the periodic table?",
    options: ["p-block", "s-block", "d-block", "f-block"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-inorganic-04",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "p-block",
    text: "The noble gases occupy which group?",
    options: ["group 18", "group 1", "group 17", "group 2"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-inorganic-05",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "Coordination Compounds",
    text: "The central metal ion in a coordination compound is surrounded by:",
    options: ["ligands", "isotopes", "allotropes", "structural isomers"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-inorganic-06",
    section: "Chemistry",
    topic: "Inorganic Chemistry",
    subtopic: "Coordination Compounds",
    text: "The coordination number of the complex ion [Cu(NH₃)₄]²⁺ is:",
    options: ["4", "6", "2", "1"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= CHEMISTRY — ORGANIC (9) =================
  {
    id: "bank-chem-organic-01",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Hydrocarbons",
    text: "Methane has which molecular geometry?",
    options: ["tetrahedral", "linear", "planar", "pyramidal"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-02",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Hydrocarbons",
    text: "The general formula of alkanes is:",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-03",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Hydrocarbons",
    text: "Benzene is an example of an:",
    options: ["aromatic hydrocarbon", "alkane", "alkyne", "alcohol"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-04",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Alcohols & Ethers",
    text: "The functional group of an alcohol is:",
    options: ["−OH", "−CHO", "−COOH", "−O−"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-05",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Alcohols & Ethers",
    text: "Heating ethanol with concentrated H₂SO₄ gives mainly:",
    options: ["ethene", "ethane", "methanol", "water only"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-06",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Alcohols & Ethers",
    text: "The functional group present in ethers is:",
    options: ["−O−", "−OH", "−CHO", "−COOH"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-07",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Carbonyl Compounds",
    text: "The functional group of a ketone is:",
    options: ["−CO−", "−CHO", "−COOH", "−OH"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-08",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Carbonyl Compounds",
    text: "Acetone is a:",
    options: ["ketone", "aldehyde", "carboxylic acid", "primary alcohol"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-chem-organic-09",
    section: "Chemistry",
    topic: "Organic Chemistry",
    subtopic: "Carbonyl Compounds",
    text: "Formaldehyde contains the functional group:",
    options: ["−CHO", "−CO−", "−COOH", "−OH"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= ENGLISH — GRAMMAR (7) =================
  {
    id: "bank-eng-grammar-01",
    section: "English",
    topic: "Grammar",
    subtopic: "Tenses",
    text: "Choose the correct sentence.",
    options: ["She goes to school daily.", "She go to school daily.", "She going to school daily.", "She gone to school daily."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-02",
    section: "English",
    topic: "Grammar",
    subtopic: "Tenses",
    text: "He ___ to the library yesterday.",
    options: ["went", "go", "gone", "going"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-03",
    section: "English",
    topic: "Grammar",
    subtopic: "Tenses",
    text: "They ___ football every weekend.",
    options: ["play", "plays", "played", "playing"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-04",
    section: "English",
    topic: "Grammar",
    subtopic: "Sentence Structure",
    text: "Choose the grammatically correct sentence.",
    options: ["The dog chased the cat.", "The cat chased the dog the.", "Chased the dog the cat.", "The dog the cat chased."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-05",
    section: "English",
    topic: "Grammar",
    subtopic: "Sentence Structure",
    text: "The book ___ on the table.",
    options: ["is", "are", "be", "am"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-06",
    section: "English",
    topic: "Grammar",
    subtopic: "Active & Passive",
    text: "Choose the passive form of “The cat eats the fish.”",
    options: ["The fish is eaten by the cat.", "The cat is eaten by the fish.", "The fish eats the cat.", "The cat was eaten by the fish."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-grammar-07",
    section: "English",
    topic: "Grammar",
    subtopic: "Active & Passive",
    text: "“She writes a letter” in the passive voice is:",
    options: ["A letter is written by her.", "A letter writes her.", "She is written by a letter.", "A letter was written by her."],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= ENGLISH — VOCABULARY (6) =================
  {
    id: "bank-eng-vocab-01",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Synonyms",
    text: "Choose the synonym of RAPID.",
    options: ["Fast", "Slow", "Quiet", "Heavy"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-vocab-02",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Synonyms",
    text: "Choose the synonym of HAPPY.",
    options: ["Joyful", "Sad", "Angry", "Tired"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-vocab-03",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Antonyms",
    text: "Choose the antonym of HOT.",
    options: ["Cold", "Warm", "Burning", "Boiling"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-vocab-04",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Antonyms",
    text: "Choose the antonym of RICH.",
    options: ["Poor", "Wealthy", "Full", "Happy"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-vocab-05",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Idioms",
    text: "To “bite the dust” means to:",
    options: ["fail or be defeated", "celebrate loudly", "hurry up", "eat quickly"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-vocab-06",
    section: "English",
    topic: "Vocabulary",
    subtopic: "Idioms",
    text: "“A blessing in disguise” is:",
    options: ["a hidden benefit", "an obvious curse", "a religious gift", "a costly mistake"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= ENGLISH — COMPREHENSION (5) =================
  {
    id: "bank-eng-comp-01",
    section: "English",
    topic: "Comprehension",
    subtopic: "Passage Reading",
    text: "Read: “The sky darkened and rain began to fall.” What is happening?",
    options: ["It is starting to rain.", "The sun is shining.", "Snow is falling.", "The storm has ended."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-comp-02",
    section: "English",
    topic: "Comprehension",
    subtopic: "Passage Reading",
    text: "Read: “She packed her bags and checked the train schedule.” What is she likely doing?",
    options: ["Traveling", "Cooking", "Reading", "Sleeping"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-comp-03",
    section: "English",
    topic: "Comprehension",
    subtopic: "Passage Reading",
    text: "Read: “The plant wilted and its leaves turned brown.” What likely happened?",
    options: ["It lacked water.", "It was struck by lightning.", "It was singing.", "It was painted."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-comp-04",
    section: "English",
    topic: "Comprehension",
    subtopic: "Inference",
    text: "“He arrived drenched.” What can be inferred?",
    options: ["It was raining.", "He was swimming.", "He spilled water.", "He was crying."],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-eng-comp-05",
    section: "English",
    topic: "Comprehension",
    subtopic: "Inference",
    text: "“The crowd cheered as the team entered the stadium.” What is implied?",
    options: ["The team is popular.", "The stadium is empty.", "The team lost.", "The crowd is angry."],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= INTELLIGENCE — LOGICAL (8) =================
  {
    id: "bank-int-logical-01",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Series",
    text: "Next in the series 3, 6, 12, 24, … ?",
    options: ["48", "36", "30", "42"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-02",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Series",
    text: "Next in the series 2, 4, 8, 16, … ?",
    options: ["32", "24", "30", "20"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-03",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Series",
    text: "Next in the series 1, 4, 9, 16, … ?",
    options: ["25", "20", "24", "30"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-04",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Analogies",
    text: "Book is to Reading as Pen is to:",
    options: ["Writing", "Eating", "Sleeping", "Running"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-05",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Analogies",
    text: "Doctor is to Hospital as Teacher is to:",
    options: ["School", "Office", "Factory", "Farm"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-06",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Analogies",
    text: "Ice is to Cold as Fire is to:",
    options: ["Hot", "Bright", "Fuel", "Smoke"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-07",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Coding-Decoding",
    text: "If CAT is coded as 24 (A = 1, B = 2, …), then DOG is coded as:",
    options: ["26", "24", "30", "20"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-logical-08",
    section: "Intelligence",
    topic: "Logical Reasoning",
    subtopic: "Coding-Decoding",
    text: "If APPLE is coded as 50 (A = 1, B = 2, …), then ORANGE is coded as:",
    options: ["60", "55", "50", "65"],
    correctIndex: 0,
    isPlaceholder: false,
  },

  // ================= INTELLIGENCE — NON-VERBAL (4) =================
  {
    id: "bank-int-nonverbal-01",
    section: "Intelligence",
    topic: "Non-Verbal",
    subtopic: "Pattern Completion",
    text: "A square rotated 90 degrees still looks like:",
    options: ["a square", "a triangle", "a circle", "a line"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-nonverbal-02",
    section: "Intelligence",
    topic: "Non-Verbal",
    subtopic: "Pattern Completion",
    text: "The next shape in the sequence ○, △, □, ○, △, … is:",
    options: ["□", "○", "△", "☆"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-nonverbal-03",
    section: "Intelligence",
    topic: "Non-Verbal",
    subtopic: "Mirror Images",
    text: "The image of the letter A in a vertical mirror looks most like:",
    options: ["A (nearly unchanged)", "a reversed E", "a backward K", "a mirrored M"],
    correctIndex: 0,
    isPlaceholder: false,
  },
  {
    id: "bank-int-nonverbal-04",
    section: "Intelligence",
    topic: "Non-Verbal",
    subtopic: "Mirror Images",
    text: "A person facing north looks into a vertical mirror mounted on the north wall. The image appears to face:",
    options: ["south", "north", "east", "west"],
    correctIndex: 0,
    isPlaceholder: false,
  },
];
